- name: setup consul server
  docker: 
    name: "{{ consul['name'] }}_main"
    docker_url: "{{ docker_host_url }}"
    image: consul
    state: started
    net: host
    command: agent -client 0.0.0.0 -server -bootstrap -ui -advertise {{ consul['ip'] }}
- name: Pull and run registrator container
  docker:
    name: "{{ consul['name'] }}_registrator"
    docker_url: "{{ docker_host_url }}"
    net: host
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip {{ consul['ip'] }} consul://{{ consul['ip'] }}:8500"