---
- hosts: ci_server
  pre_tasks:
    - name: check homebrew
      stat: path=/usr/local/bin/brew
      register: brew_present
    - name: install Homebrew
      shell: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      when: brew_present == false
    - homebrew: name={{ item }} state=present
      with_items:
        - mongo
    - name: Start services at login
      file: src=/usr/local/opt/mongodb/homebrew.mxcl.mongodb.plist path=~/Library/LaunchAgents/homebrew.mxcl.mongo.plist state=link force=yes
    - name: Setup launch agents for services
      command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongo.plist
  roles:
    - nodejs
    - ci_server