- name: stash repo changes
  shell: "if -z [ ../{{ item }} ]; then cd ../{{ item }} && git stash; fi"
  changed_when: "command_result.stdout != 'No local changes to save'"
  register: command_result
  with_items:
    - boundary_file_service
    - web
    - user_service

- name: fetch git repos
  git: repo=git@git.thoughtworks.net:beruni/{{ item }}.git dest=../{{ item }}
  with_items:
    - boundary_file_service
    - web
    - user_service
