---
dependencies:
  - role: mongo
    mongo:
      port: "{{ boundaries['mongo_port'] }}"
      name: "boundary_mongo"
  - role: node_server
    node_server:
      port: "{{ boundaries['node_server_port'] }}"
      name: "boundary_file_service"