- name: setup {{ node_server['name'] }} node server
  docker: 
    name: "{{ node_server['name'] }}"
    docker_url: "{{ docker_host_url }}"
    hostname: "{{ node_server['name'] }}"
    image: node:{{ node_version }}
    ports: "{{ node_server['port'] }}:{{ node_server['port'] }}"
    expose: "{{ node_server['port'] }}"
    links: "{{ node_server['mongo_name'] }}:mongo"
    state: reloaded
    volumes:
      - "{{ playbook_dir }}/../{{ node_server['name'] }}:/apps/{{ node_server['name'] }}"
    command: "/bin/bash -c \"env && ls -la /apps/{{ node_server['name'] }} && cd /apps/{{ node_server['name'] }} && DISCOVERY_SERVICE_HOST={{ node_server['discovery_service_host'] }} npm start\""
        