---
dependencies:
  - role: mongo
    mongo:
      port: "{{ users['mongo_port'] }}"
      name: "users_mongo"
  - role: node_server
    node_server:
      port: "{{ users['node_server_port'] }}"
      mongo_port: "{{ users['mongo_port'] }}"
      name: "user_service"