---
dependencies:
  - role: mongo
    mongo:
      name: "users_mongo"
  - role: node_server
    node_server:
      port: "{{ users['node_server_port'] }}"
      mongo_name: "users_mongo"
      name: "user_service"
      discovery_service_host: "{{ apps['discovery_service_host'] }}"